name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Installing Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        python-version: '3.9'
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8
    
    - name: Install Packages
      run: poetry install --with dev
    
    - name: Running Linter
      run: make lint
