name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8
    
    - name: Install Packages
      run: poetry install --with dev
    
    - name: Running Linter
      run: make lint
